### ISSUE TITLE
Not able to see all the groups and my group as well

### ISSUE THREAD

**Issue by mr-sesquipedalian** [TG-ToolsFree/Telegram-Adder-Scraper-Members-NEW-2023-FREE#10]
Hi Team,

I am not able to see the group in which I have to add members and only see 2-3 groups pls help

**Comment by TG-ToolsFree** [comment]
Hello,

you need to join the groups with your scraper-account. It's the first account with which you are logging in into the tool. If you need more help, feel free to contact us on Telegram: t.me/SubAdder

**Comment by TG-ToolsFree** [comment]
Hello,

you need to join the groups with your scraper-account. It's the first account with which you are logging in into the tool. If you need more help, feel free to contact us on Telegram: t.me/SubAdder
