### ISSUE TITLE
The Group didnt show but when scraping it show

### ISSUE THREAD

**Issue by fangfang94** [TG-ToolsFree/Telegram-Adder-Scraper-Members-NEW-2023-FREE#11]
TG CHANNEL: @TGToolsFree    |    TG SUPPORT: @SubAdder
                        Version: 1.4

┏━━━━━━━━━━━━━━━━━━━━━━━━━━╍┅●TG-TOOLS●┅╍━━━━━━━━━━━━━━━━━━━━━━━━━
┃
┠──● LOGIN MENU
┃      └── [1] LOGIN ACCOUNTS
┃          [2] DELETE ACCOUNTS (ONLY FROM THIS APP)
┠──● SCRAPER MENU
┃      └── [3] SCRAPE MEMBERS FROM TARGETED GROUP
┠──● ADDER MENU
┃      └── [4] ADD MEMBERS TO YOUR GROUP
┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━╍┅●TG-TOOLS●┅╍━━━━━━━━━━━━━━━━━━━━━━━━━

Choose an Option: 4
[+] Accounts getting ready...

[+] Account ready: 601xx
[+] Account ready: 601xx
[+] Account ready: 601xx
[+] Account ready: 6011xx
[+] Account ready: 601xxx

[+] Total Accounts: 5
[+] Please select the group to add members to:

[+] Please enter the corresponding number:

**Comment by TG-ToolsFree** [comment]
Hey,

you are using an outdated version of our tool. Download the newest version here: https://github.com/TG-ToolsFree/Telegram-Adder-Scraper-Members-NEW-2023-FREE 
If you still need help, feel free to contact us on Telegram: https://t.me/SubAdder
