### ISSUE TITLE
ModuleNotFoundError: No module named 'filestack'

### ISSUE THREAD

**Issue by xsaad67** [TG-ToolsFree/Telegram-Adder-Scraper-Members-NEW-2023-FREE#12]
Getting an error of ModuleNotFoundError: No module named 'filestack'

**Comment by TG-ToolsFree** [comment]
You need to install all requirements with this command: pip install -r requirements.txt
Make sure to read the INSTALL.txt file.
If you still need help, feel free to contact us on Telegram: https://t.me/SubAdder
