### ISSUE TITLE
"sqlite3.OperationalError: database is locked "There is a lock in the SQLite database used by Telethon to store user sessions.

### ISSUE THREAD

**Issue by jretro4** [TG-ToolsFree/Telegram-Adder-Scraper-Members-NEW-2023-FREE#13]
![image_2023-08-12_18-49-52](https://github.com/TG-ToolsFree/Telegram-Adder-Scraper-Members-NEW-2023-FREE/assets/134271603/6663816a-50ed-4066-80dd-58bb5cf6be0e)

When I try to choose option 4 (ADD MEMBERS TO YOUR GROUP), I get this error. This indicates that the SQLite database is currently locked and cannot be accessed due to an ongoing operation.

Do you know why this error appears? Thank you very much for your time, I hope you will help me in exchange for BTC.

**Comment by jretro4** [comment]
This happens right after selecting which group I want to add the members to

**Comment by TG-ToolsFree** [comment]
This is a bug from our tool. We will fix this and release a new version of the tool soon. For now, delete the session file, which is causing this bug and login with other accounts until it gets fixed.
