### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by iammuhammadnoumankhan** [TG-ToolsFree/Telegram-Adder-Scraper-Members-NEW-2023-FREE#14]
return future.result()
           ^^^^^^^^^^^^^^^
  File "main1.61.py", line 108, in main
IndexError: list index out of range

**Comment by TG-ToolsFree** [comment]
Make sure to write your api id and hash into credentials.csv
Open credentials example.csv to see the format.

**Comment by iammuhammadnoumankhan** [comment]
I did but it give the same error message again.
Can you plz run it there.

And error shows in line 108
List index out of range.

**Comment by TG-ToolsFree** [comment]
Send me a pic of credentials.csv to my Telegram account: https://t.me/SubAdder

**Comment by iammuhammadnoumankhan** [comment]
Thank you so much
I fix it, there were issue in excel file format,
But now it's fixed
