### ISSUE TITLE
banned accounts

### ISSUE THREAD

**Issue by xone247** [TG-ToolsFree/Telegram-Adder-Scraper-Members-NEW-2023-FREE#16]
despite having many api id and api hash when i add a new account it just automatically bans the account without me scraping nor adding members

**Comment by TG-ToolsFree** [comment]
Then Telegram doesnt like that specific account. You need to use aged accounts.

**Comment by xone247** [comment]
the accounts are old accounts

**Comment by kiko19871312** [comment]
I have same problem, aged accounts but instantly getting banned as soon as I log in them to the script..
