### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by OmarYuusf** [TG-ToolsFree/Telegram-Adder-Scraper-Members-NEW-2023-FREE#18]
i got this error when i run "python3 main.pyc" >> 3

![image](https://github.com/TG-ToolsFree/Telegram-Adder-Scraper-Members-NEW-2023-FREE/assets/57051225/b5b4659c-cb62-4d78-a62d-17d28d1fcca5)

**Comment by TG-ToolsFree** [comment]
Make sure to write your api id and hash into credentials.txt. Check the file credentials_example.txt out to see the correct format.
