### ISSUE TITLE
RuntimeError: Bad magic number in .pyc file

### ISSUE THREAD

**Issue by omangi** [TG-ToolsFree/Telegram-Adder-Scraper-Members-NEW-2023-FREE#20]
I'm running python Python 3.8.10 on ubuntu 20.04.

Have no compatibily with my system ?

**Comment by kiko19871312** [comment]
It is as I can say. I'm using same version of python, win11 OS..

**Comment by omangi** [comment]
> It is as I can say. I'm using same version of python, win11 OS..

and it's working ?

**Comment by kiko19871312** [comment]
Not since 12 hours ago. It was working fine.

**Comment by TG-ToolsFree** [comment]
You have to update your Python

**Comment by omangi** [comment]
Great, worked wih Python 3.11.5

**Comment by TechUX** [comment]
The .pyc file is compiled python program.

It only work only that version of python in which it is written and compiled.

This .pyc program is written in Python 3.1 version, so does not works with above or below version

**Comment by TG-ToolsFree** [comment]
Update Python to 3.12
