### ISSUE TITLE
main.py file crashing

### ISSUE THREAD

**Issue by kiko19871312** [TG-ToolsFree/Telegram-Adder-Scraper-Members-NEW-2023-FREE#21]
main.py file is crashing and it's not giving a chance to start a script at all. 
Was working 12 hours ago, and it just went in crashes. 

Hope you will fix it soon! :) 

Screenshots: 

https://i.imgur.com/uxRG4dz.png

https://i.imgur.com/GNneNad.png

**Comment by kiko19871312** [comment]
Suddenly just started working again after 14 hours again.. I dont know what is going on really... 👯

**Comment by TG-ToolsFree** [comment]
You need to work with main.pyC you forgot the c.

**Comment by kiko19871312** [comment]
What? pyC ? since when ?

**Comment by kiko19871312** [comment]
And now it's not working again, again is crashing, since the moment you've commented here, I swear ! :D

**Comment by TG-ToolsFree** [comment]
Probably because a new update is out now. Otherwise, make sure to check the format of the api and also make sure to connect enough accounts with the tool

**Comment by kiko19871312** [comment]
Okay, I must download updated main.py now in order to work, because script isn't pushing updates for my main.py ... Format of api and hash is good, I have 35 api accounts and 65 telegram profiles.

**Comment by kiko19871312** [comment]
Yeah, now I can't see one of my groups I need to use with script. Why that can be ?
