### ISSUE TITLE
main.py again with bug...

### ISSUE THREAD

**Issue by kiko19871312** [TG-ToolsFree/Telegram-Adder-Scraper-Members-NEW-2023-FREE#25]
I have latest Python 3.12 and still getting bad magic number in .pyc file, and also getting python: can't open file 'main.py': [Errno 2] No such file or directory

**Comment by TG-ToolsFree** [comment]
You need to open cmd in the same folder as the tool. Thats not a bug from the tool. It cant find the file.

**Comment by kiko19871312** [comment]
I do open cmd in the same folder man. Im not that stupid.

**Comment by kiko19871312** [comment]
https://i.imgur.com/gDP2C4a.png

**Comment by kiko19871312** [comment]
https://i.imgur.com/hf2Ged0.png

**Comment by kiko19871312** [comment]
The code is not working

**Comment by TG-ToolsFree** [comment]
Your system cant find the file main.pyc therefore it cant run it. Download main.pyc here and paste it into that folder: https://github.com/TG-ToolsFree/Telegram-Adder-Scraper-Members-NEW-2023-FREE/blob/main/main.pyc

**Comment by kiko19871312** [comment]
I always download new main.pyc file and paste it in that folder, every time this happens or you push update on main.pyc file, I must download new one it wont update automatically. I downloaded it now again and paste it in folder with whole script but it just dont wanna run

**Comment by kiko19871312** [comment]
Okay, I managed to run it again... I don't know how but I just did...
