### ISSUE TITLE
main.py bugs?

### ISSUE THREAD

**Issue by kiko19871312** [TG-ToolsFree/Telegram-Adder-Scraper-Members-NEW-2023-FREE#27]
Is it me, or something is wrong with code again? anything else I try to run it just crashes the code down from functioning, but not crashing only when I want to log in new accs. Any thoughts what it might be ? All other functions crashing it down....

Trying "add members" results with this: 
https://i.imgur.com/6YAv0sB.png

Trying to scrape members results like this:
https://i.imgur.com/ZneQMZc.png

Trying to delete accounts :
https://i.imgur.com/t9TJl9C.png

Only the LOG IN option works : 
https://i.imgur.com/Vwngokl.png

**Comment by TG-ToolsFree** [comment]
Hey, that error is because it is expecting a specific format on numbers.csv. Check your numbers.csv file make sure the format is correct. If that still doesnt help, delete all lines of numbers.csv manually and login with your accounts again.

**Comment by kiko19871312** [comment]
Okay I will try, thank you !
