### ISSUE TITLE
session accounts instant ban

### ISSUE THREAD

**Issue by kiko19871312** [TG-ToolsFree/Telegram-Adder-Scraper-Members-NEW-2023-FREE#29]
Hi there, it seems that Telegram changed some of their policy, every and each account logged through session file format instead of tdata,  instantly gets banned from telegram. Are you able to change this and make script uses tdata folder instead of session formats? I've lost 100 accounts because of this, and I can't use the script anymore untill you resolve this issue, which is a big issue right now.

Thanks for your project it's awesome btw!

**Comment by TG-ToolsFree** [comment]
It is not possible to use tdata instead of a .session file. For us, everything is working fine without any bans. This seems like you got flagged or you have unintentionally used the same accounts on different tools at the same time, try to avoid that. Make sure to change your api just in case. Use older accounts with different country codes other than which you were using.

**Comment by kiko19871312** [comment]
I never used same accounts for different tools, I was using them only for your tool. How do you mean I'm got flagged, do you mean my IP address, or my PC as a machine ? Because when I log in with accounts with different PC , it doesn't get banned at all. 
I use older accounts over 5 days, with daily chat interactions... I just don't get it, I've even reinstalled whole Windows OS this morning thinking that it is because of flagged PC, but it seems it's not, in other hand I don't think it's IP either because I've tried 3 different wifi networks - same thing- instant ban when logging to the script with accounts. I'm always using good quality VPN service, and also i'm using different proxy IPs for each TG account (Mtproto public proxy list), but even now without Proxy, without VPN, with fresh Win11 OS and fresh internet network, I'm getting banned same way. I just don't get it. 
I did DM you in Tg app but 3 days past and I haven't got any responds from you, that's why I'm typing here. 

Hope you can help to resolve this problem as it starts driving me nuts 😅

**Comment by kiko19871312** [comment]
Hey, I really don't understand why is it happening, but any PC with any WiFi gives me instant ban to any TG profile i use to log in to your script. No matter if it's new or old account, I've lost over 100 accounts with your script, but I still can't understand WHY. PLEASE HELP

**Comment by TG-ToolsFree** [comment]
> I never used same accounts for different tools, I was using them only for your tool. How do you mean I'm got flagged, do you mean my IP address, or my PC as a machine ? Because when I log in with accounts with different PC , it doesn't get banned at all. I use older accounts over 5 days, with daily chat interactions... I just don't get it, I've even reinstalled whole Windows OS this morning thinking that it is because of flagged PC, but it seems it's not, in other hand I don't think it's IP either because I've tried 3 different wifi networks - same thing- instant ban when logging to the script with accounts. I'm always using good quality VPN service, and also i'm using different proxy IPs for each TG account (Mtproto public proxy list), but even now without Proxy, without VPN, with fresh Win11 OS and fresh internet network, I'm getting banned same way. I just don't get it. I did DM you in Tg app but 3 days past and I haven't got any responds from you, that's why I'm typing here.
> 
> Hope you can help to resolve this problem as it starts driving me nuts 😅

I have never seen this issue on my side, therefore I can only guess. If it is perfectly working with different PC's but not that one specific PC, then it is possible that they have flagged your MAC-Address. Flagges means being shadowbanned, in other words = blacklisted. Is it possible to get unflagged? I dont know, Telegram can always change their system. You will need to be creative and experiment.
