### ISSUE TITLE
Can't figure it out why I'm getting banned

### ISSUE THREAD

**Issue by kiko19871312** [TG-ToolsFree/Telegram-Adder-Scraper-Members-NEW-2023-FREE#31]
I can't figure it out why I'm getting banned with any profile I try to use with this script. It started 7 days ago, since then I can't use script anymore because if I log in with TG account - I'm instantly banned, but if I don't log in to script, telegram account stays as it is - normal. 

Can you explain why is this happening? 
BTW, I've tried different PCs, different internet connections, different VPNs and Proxies, but nothing helps. It seems it has to do something with script, I'm not sure anymore, PLEASE help!

**Comment by amiiko** [comment]
you are not alone guys i am getting banned too i have try with too many new ip address and pc and accounts. so far i lost 9 accounts.

please contact me on telegram and lets figure this out together @amanuel_kev

**Comment by TG-ToolsFree** [comment]
Make sure that Telegram didnt flag your country, some countries like Uzbekistan got flagged and get insta bans. Doesnt matter which schript they are using.

**Comment by kiko19871312** [comment]
If Telegram did flagged my country my regular Telegram account would also be banned, and not only accounts I'm trying to use with this script. No matter which country code, IP, PC, VPN I am using, every account that logs in to this script is banned, and I bet those guys are not from same country as I am and they are also getting instant bans like me... So I'm not the only one (at least that) . What would be a dynamic solution for this kind of issue? I don't get it...

**Comment by amiiko** [comment]
yes bro i am from ethiopia and i have one account activley working now with api but when i try to get anew account it bannes me every time.

**Comment by kiko19871312** [comment]
I'm from Europe, and I'm using South Africa phone numbers for accounts, and also using USA numbers for accounts, and I really don't know what to do more in order to avoid this problem

**Comment by amiiko** [comment]
how are your accounts since created?

**Comment by kiko19871312** [comment]
Created online
