### ISSUE TITLE
i am getting bannned too with out even doing anything the moment the session created boom my accoute get banned

### ISSUE THREAD

**Issue by amiiko** [TG-ToolsFree/Telegram-Adder-Scraper-Members-NEW-2023-FREE#32]
i am getting bannned too with out even doing anything the moment the session created boom my accoute get banned

**Comment by TG-ToolsFree** [comment]
This is a problem of Telegram changing their limits. It is dynamic, which means you will not get the same result everytime. If you get banned like that, you most likely got flagged. Either your ip address, your mac address or even maybe the country you live in could make problems. If the limit of Telegram is dynamic, which it is, then you will need dynamic solutions with dynamic changes. Use different country area codes, use different api's, use different ip's and so on...
