### ISSUE TITLE
filestack.exceptions.FilestackHTTPError: Your app is currently blocked due to reaching a free limit or unpaid invoice

### ISSUE THREAD

**Issue by Gerry9797** [TG-ToolsFree/Telegram-Adder-Scraper-Members-NEW-2023-FREE#33]
Hello, after the version upgrading when I launch main.pyc this error appears:

filestack.exceptions.FilestackHTTPError: {"error":"Your app is currently blocked due to reaching a free limit or unpaid invoice. To upgrade your account or pay any outstanding invoices, login to your Filestack account here: https://dev.filestack.com/login/","timestamp":1698929522}

**Comment by TG-ToolsFree** [comment]
Its fixed. Restart your tool to automatically update it.
