### ISSUE TITLE
Still getting banned everytime 

### ISSUE THREAD

**Issue by kiko19871312** [TG-ToolsFree/Telegram-Adder-Scraper-Members-NEW-2023-FREE#36]
I'm still getting instant bans when I log in to a script. I've tried running in it in VM - same thing- instant ban. Tried running the script in VPS - same thing instant bans. Tried different PCs, different networks, different VPNs, proxies, phone numbers, API keys. Nothing helps... What I can do more in order to run the script again with no instant bans? Please help to resolve this issue.

**Comment by TG-ToolsFree** [comment]
We can't do anything about being limited. It is working perfectly for us but for some people its harder. Its different for everyone and dynamic aswell. It is even possible that your country is blacklisted by Telegram.
