### ISSUE TITLE
The groups are not displayed in the terminal

### ISSUE THREAD

**Issue by Mathbate** [TG-ToolsFree/Telegram-Adder-Scraper-Members-NEW-2023-FREE#37]
Hello, when I perform the usual command to scrape and add members to a group, the groups are not displayed in the terminal.
<img width="363" alt="Capture d’écran 2023-11-09 à 23 26 11" src="https://github.com/TG-ToolsFree/Telegram-Adder-Scraper-Members-NEW-2023-FREE/assets/150047953/c338c31d-e4cd-41b3-ad1c-7df87728f4a0">

**Comment by TG-ToolsFree** [comment]
Hey, make sure to login with the accounts first. And check the numbers.csv file. The first account in that file is your scraper account. Make sure you have joined into the desired groups with that account.
