### ISSUE TITLE
Telegram Banned account after using script

### ISSUE THREAD

**Issue by sahilkundu** [TG-ToolsFree/Telegram-Adder-Scraper-Members-NEW-2023-FREE#41]
![IMG_0176](https://github.com/TG-ToolsFree/Telegram-Adder-Scraper-Members-NEW-2023-FREE/assets/71582663/ac3b9148-c357-4bf0-9fc0-983e03c5f005)

**Comment by TG-ToolsFree** [comment]
This is a problem of Telegram changing their limits. It is dynamic, which means you will not get the same result everytime. If you get banned like that, you most likely got flagged. Either your ip address, your mac address or even maybe the country you live in could make problems. If the limit of Telegram is dynamic, which is, then you will need dynamic solutions with dynamic changes. Use different country area codes, use different api's, use different ip's and so on...
