### ISSUE TITLE
Not using all account when adding members

### ISSUE THREAD

**Issue by johnlam602** [TG-ToolsFree/Telegram-Adder-Scraper-Members-NEW-2023-FREE#42]
Hi, when i am going add members to group
I find the tool never use all the account i loged in.(All is not limited account)
And also never reach the limit that i entered

For example,i had log in 10 account ,switch account after adding 5 members,max count is 20 per account
So there should be 4 loop until it finish

However the tool always just using 4-5accounts every loop,switching account after just adding 1-2 memebers and stop at 1-2 loop

Re login is also not working

Please help,thanks alot

**Comment by TG-ToolsFree** [comment]
Thanks, we will look into this and fix it.
