### ISSUE TITLE
No such file in your directory

### ISSUE THREAD

**Issue by Mathbate** [TG-ToolsFree/Telegram-Adder-Scraper-Members-NEW-2023-FREE#46]
Hi i just download the tool again, started it, installed the credentials but now it says : 
/Library/Frameworks/Python.framework/Versions/3.12/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/mathis/Desktop/Telegram-Adder-Scraper-Members-NEW-2023-FREE-main/./main.py': [Errno 2] No such file or directory

It was working before...
Thanks for your help,
Mathis.

**Comment by TG-ToolsFree** [comment]
Hey, make sure you have written everything correctly. Command is:
python main.pyc
