### ISSUE TITLE
error while trying to scrape members

### ISSUE THREAD

**Issue by dives121** [TG-ToolsFree/Telegram-Adder-Scraper-Members-NEW-2023-FREE#47]
i had 2 API_ID AND API_HASH in the credential.txt file. ad also login an account which has private and public group. 
so i run the main.pyc , i chose the option 1. to login the account, after successful login. i ran the main.pyc again,chose option 3 to scrape members from tergeted group. i get the below message.  kindly help with this. i just want to test this and be sure it's working before i purchase the premium tool. as it has features i'll be needing. thank you.
Server sent a very new message with ID 7317306745616850949, ignoring (see FAQ for details)
Server sent a very new message with ID 7317306745655334913, ignoring (see FAQ for details)

**Comment by TG-ToolsFree** [comment]
Make sure to join into public groups with the first account with which you have connected to the tool. After that, run the tool again.
This tool is very limited. Use the premium tool for no restrictions: https://github.com/TG-ToolsFree/Telegram-Adder-Scraper-BulkMessageSender-Forwarder-FakeViews-Reporter-ChannelCopy_All-In-1-Tool-2023
You can scrape also private groups, enter also just the link or the username. +33 more features.
