### ISSUE TITLE
Adding members

### ISSUE THREAD

**Issue by MisterKhan79** [TG-ToolsFree/Telegram-Adder-Scraper-Members-NEW-2023-FREE#7]
Hi, So I have scraped a group which has lets say 1000 members but I only have 10 telegram accounts and hence I can only add 500 members to my group. How do I overcome this.

Also if I try to do it in 2 days then issue is the script starts adding members which are already added (and I cannot even edit the "teammember" csv) so how do I over come this other than adding (logging in) more telegram accounts on the app

And, when an account gets banned, the script quits the process, so even if I wanna use again, it adds members from begininng (which are already in my group) and I can never get to adding all members sice it keeps starting from the top.

**Comment by TG-ToolsFree** [comment]
You can't overcome that. It's not a limit by the tool, it's a limit by Telegram. Invite until the limits have been reached, continue adding the next day. For now, delete the added members manually from the file, we will implement auto-deletion soon.
