### ISSUE TITLE
RuntimeError: Bad magic number in .pyc file

### ISSUE THREAD

**Issue by fangfang94** [TG-ToolsFree/Telegram-Adder-Scraper-Members-NEW-2023-FREE#9]
![image](https://github.com/TG-ToolsFree/Telegram-Adder-Scraper-Members-NEW-2023-FREE/assets/29105455/db6497be-80b1-4736-ac85-beed5217350b)

**Comment by fangfang94** [comment]
![image](https://github.com/TG-ToolsFree/Telegram-Adder-Scraper-Members-NEW-2023-FREE/assets/29105455/30474d5f-0cde-4784-8433-9bff86887b65)

**Comment by TG-ToolsFree** [comment]
You need to update your Python version.
